In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\aksha\Downloads\customer_shopping_behavior_100_records.csv")

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,10002,65,Female,Blouse,Clothing,82,Boston,S,Brown,Winter,2.8,Yes,Free Shipping,No,No,14,Credit Card,Weekly
1,10003,50,Male,Shoes,Footwear,70,Austin,S,Blue,Winter,4.1,No,Express,Yes,Yes,45,PayPal,Bi-Weekly
2,10004,24,Male,Sneakers,Footwear,117,Miami,S,Gray,Spring,3.4,Yes,Store Pickup,Yes,Yes,6,PayPal,Annually
3,10005,30,Male,Hat,Accessories,31,Los Angeles,XL,Green,Winter,3.1,Yes,Express,Yes,Yes,42,Debit Card,Monthly
4,10006,60,Female,Handbag,Accessories,38,Phoenix,M,Yellow,Spring,4.1,No,Standard,Yes,Yes,38,Credit Card,Monthly

In [2]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,100.000000,100.000000,100.000000,100.000000,100.000000
mean,10051.500000,41.560000,89.660000,3.777000,25.170000
std,29.011492,15.757198,37.031033,0.672978,15.284544
min,10002.000000,19.000000,21.000000,2.500000,0.000000
25%,10026.750000,26.750000,54.500000,3.200000,12.000000
50%,10051.500000,39.500000,93.000000,3.750000,26.000000
75%,10076.250000,55.000000,117.250000,4.325000,38.000000
max,10101.000000,69.000000,149.000000,4.900000,50.000000

In [3]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [4]:
df.columns=df.columns.str.lower()

In [5]:
df.head()

,customer id,age,gender,item purchased,category,purchase amount (usd),location,size,color,season,review rating,subscription status,shipping type,discount applied,promo code used,previous purchases,payment method,frequency of purchases
0,10002,65,Female,Blouse,Clothing,82,Boston,S,Brown,Winter,2.8,Yes,Free Shipping,No,No,14,Credit Card,Weekly
1,10003,50,Male,Shoes,Footwear,70,Austin,S,Blue,Winter,4.1,No,Express,Yes,Yes,45,PayPal,Bi-Weekly
2,10004,24,Male,Sneakers,Footwear,117,Miami,S,Gray,Spring,3.4,Yes,Store Pickup,Yes,Yes,6,PayPal,Annually
3,10005,30,Male,Hat,Accessories,31,Los Angeles,XL,Green,Winter,3.1,Yes,Express,Yes,Yes,42,Debit Card,Monthly
4,10006,60,Female,Handbag,Accessories,38,Phoenix,M,Yellow,Spring,4.1,No,Standard,Yes,Yes,38,Credit Card,Monthly

In [7]:
labels=['Young age','Adult','Middle age','Senior']
df["age-group"]=pd.qcut(df['age'],q=4,labels=labels)

In [9]:
df[['age','age-group']].head(10)

   age   age-group
0   65      Senior
1   50  Middle age
2   24   Young age
3   30       Adult
4   60      Senior
5   22   Young age
6   55  Middle age
7   42  Middle age
8   64      Senior
9   38       Adult

In [11]:
labels=pd.Series(['Young age','Adult','Middle age','Senior'])
df['age-group1']=labels

In [14]:
df[['age-group1']].head(10)

   age-group1
0   Young age
1       Adult
2  Middle age
3      Senior
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN

In [16]:
df.head(10)

,customer id,age,gender,item purchased,category,purchase amount (usd),location,size,color,season,review rating,subscription status,shipping type,discount applied,promo code used,previous purchases,payment method,frequency of purchases,age-group,age-group1
0,10002,65,Female,Blouse,Clothing,82,Boston,S,Brown,Winter,2.8,Yes,Free Shipping,No,No,14,Credit Card,Weekly,Senior,Young age
1,10003,50,Male,Shoes,Footwear,70,Austin,S,Blue,Winter,4.1,No,Express,Yes,Yes,45,PayPal,Bi-Weekly,Middle age,Adult
2,10004,24,Male,Sneakers,Footwear,117,Miami,S,Gray,Spring,3.4,Yes,Store Pickup,Yes,Yes,6,PayPal,Annually,Young age,Middle age
3,10005,30,Male,Hat,Accessories,31,Los Angeles,XL,Green,Winter,3.1,Yes,Express,Yes,Yes,42,Debit Card,Monthly,Adult,Senior
4,10006,60,Female,Handbag,Accessories,38,Phoenix,M,Yellow,Spring,4.1,No,Standard,Yes,Yes,38,Credit Card,Monthly,Senior,NaN
5,10007,22,Male,Parka,Outerwear,100,Miami,M,Green,Summer,4.1,No,Standard,No,No,13,Cash,Every 3 Months,Young age,NaN
6,10008,55,Female,Belt,Accessories,122,Los Angeles,S,White,Summer,3.0,No,Standard,No,No,23,Venmo,Every 3 Months,Middle age,NaN
7,10009,42,Female,Jacket,Clothing,84,Atlanta,L,Yellow,Spring,4.7,Yes,Express,No,No,35,Venmo,Bi-Weekly,Middle age,NaN
8,10010,64,Female,Hoodie,Outerwear,148,Phoenix,M,Blue,Fall,2.9,No,Standard,No,No,48,Cash,Every 3 Months,Senior,NaN
9,10011,38,Female,Skirt,Clothing,24,Phoenix,M,Black,Summer,4.8,No,Store Pickup,No,No,7,Credit Card,Weekly,Adult,NaN

In [20]:
df=df.drop('age-group1',axis=1)

In [21]:
df.head()

,customer id,age,gender,item purchased,category,purchase amount (usd),location,size,color,season,review rating,subscription status,shipping type,discount applied,promo code used,previous purchases,payment method,frequency of purchases,age-group
0,10002,65,Female,Blouse,Clothing,82,Boston,S,Brown,Winter,2.8,Yes,Free Shipping,No,No,14,Credit Card,Weekly,Senior
1,10003,50,Male,Shoes,Footwear,70,Austin,S,Blue,Winter,4.1,No,Express,Yes,Yes,45,PayPal,Bi-Weekly,Middle age
2,10004,24,Male,Sneakers,Footwear,117,Miami,S,Gray,Spring,3.4,Yes,Store Pickup,Yes,Yes,6,PayPal,Annually,Young age
3,10005,30,Male,Hat,Accessories,31,Los Angeles,XL,Green,Winter,3.1,Yes,Express,Yes,Yes,42,Debit Card,Monthly,Adult
4,10006,60,Female,Handbag,Accessories,38,Phoenix,M,Yellow,Spring,4.1,No,Standard,Yes,Yes,38,Credit Card,Monthly,Senior

In [23]:
frequency_mapping={
'Weekly':7,
'Bi-Weekly':14,
'Annually':365,
'Monthly':30,
'Every 3 Months':90,
'Quarterly':45,
}
df['purchase-frequent-no-of-days']=df['frequency of purchases'].map(frequency_mapping)

In [26]:
df[['frequency of purchases','purchase-frequent-no-of-days']].head(15)

   frequency of purchases  purchase-frequent-no-of-days
0                  Weekly                             7
1               Bi-Weekly                            14
2                Annually                           365
3                 Monthly                            30
4                 Monthly                            30
5          Every 3 Months                            90
6          Every 3 Months                            90
7               Bi-Weekly                            14
8          Every 3 Months                            90
9                  Weekly                             7
10               Annually                           365
11                 Weekly                             7
12                 Weekly                             7
13              Bi-Weekly                            14
14                 Weekly                             7

In [28]:
(df['discount applied']==df['promo code used']).all()

np.False_

In [30]:
df.rename(columns={'age':'customer age','gender':'customer gender'})

,customer id,customer age,customer gender,item purchased,category,purchase amount (usd),location,size,color,season,review rating,subscription status,shipping type,discount applied,promo code used,previous purchases,payment method,frequency of purchases,age-group,purchase-frequent-no-of-days
0,10002,65,Female,Blouse,Clothing,82,Boston,S,Brown,Winter,2.8,Yes,Free Shipping,No,No,14,Credit Card,Weekly,Senior,7
1,10003,50,Male,Shoes,Footwear,70,Austin,S,Blue,Winter,4.1,No,Express,Yes,Yes,45,PayPal,Bi-Weekly,Middle age,14
2,10004,24,Male,Sneakers,Footwear,117,Miami,S,Gray,Spring,3.4,Yes,Store Pickup,Yes,Yes,6,PayPal,Annually,Young age,365
3,10005,30,Male,Hat,Accessories,31,Los Angeles,XL,Green,Winter,3.1,Yes,Express,Yes,Yes,42,Debit Card,Monthly,Adult,30
4,10006,60,Female,Handbag,Accessories,38,Phoenix,M,Yellow,Spring,4.1,No,Standard,Yes,Yes,38,Credit Card,Monthly,Senior,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10097,21,Female,Sneakers,Footwear,115,Los Angeles,L,White,Summer,4.8,No,Express,No,No,35,Venmo,Every 3 Months,Young age,90
96,10098,23,Male,Boots,Footwear,135,Seattle,S,Yellow,Summer,4.8,No,Free Shipping,Yes,Yes,22,PayPal,Weekly,Young age,7
97,10099,27,Male,Sunglasses,Accessories,29,Austin,XL,Pink,Spring,4.8,No,Free Shipping,No,No,18,Credit Card,Monthly,Adult,30
98,10100,53,Female,Shoes,Footwear,48,Austin,XL,White,Spring,3.2,Yes,Next Day Air,Yes,Yes,49,Cash,Every 3 Months,Middle age,90
99,10101,54,Male,Shorts,Clothing,56,Atlanta,S,Purple,Fall,3.6,No,Free Shipping,Yes,Yes,18,Cash,Every 3 Months,Middle age,90